spring.application.name=unsolved_backend

server.servlet.context-path=/v1

# Database MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Database Redis
spring.data.redis.port=6379

# Template Engine
spring.thymeleaf.cache=false

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop